source 'https://rubygems.org'

gem 'pg'
gem 'rake'
gem 'em-postgresql-adapter', :git => 'git://github.com/leftbee/em-postgresql-adapter.git'
gem 'rack-fiber_pool',  :require => 'rack/fiber_pool'
gem "em-http-request", github: 'igrigorik/em-http-request'
gem 'em-synchrony' , :github => 'igrigorik/em-synchrony',
                    :require => ['em-synchrony', 'em-synchrony/activerecord', 'em-synchrony/em-http']
gem 'yajl-ruby'
gem 'grape'
gem 'goliath', '~> 1.0.3'
gem 'rubyzip'

group :test do
  gem 'rspec', '~> 2.13.0'
  gem 'minitest'
  gem 'rspec-rails'
  gem 'rack-test', :require => 'rack/test'
  gem 'factory_girl'
end

group :development do
  gem 'foreman'
end

# gems for automatic testing
group :autotest do
  gem 'guard-rspec'
  gem 'guard-livereload'
  #required by guard for linux
  gem 'rb-inotify'
  gem 'guard-spork'
  # if you don't have ruby with readline support
  gem 'rb-readline'
end